### ISSUE TITLE
are gerbers ok (v3.2)

### ISSUE THREAD

**Issue by alinelena** [plut0nium/0xB2#12]
I am looking into printing few of these i upload the single board and choose panelise by pcb 4x2 but then when they show me the parts placements looks like this, notice usb type c not in place... similar if I choose the panelized version from the repo.

![image](https://github.com/plut0nium/0xB2/assets/3306823/4ed13f11-3d73-4594-8164-989ba6c4d7c2)

also i notice my replacement nor does not show.. i went with this, C5258281, this check with them

**Comment by plut0nium** [comment]
The bad placement of the USB-C is a common issue, and is usually solved by JLCPCB operators during the final review.

Many people have used the gerbers without reported issue.

**Comment by alinelena** [comment]
thank you! I assumed show but I wanted to have it triple checked.
