### ISSUE TITLE
Which version of CircuitPython to be flashed ?

### ISSUE THREAD

**Issue by bharathyes** [plut0nium/0xB2#15]
Currently building a Lily58 PRO with Splinky as the controller. 

Stuck at writing the firmware to the board.

Which version of CircuitPython needs to be flashed for setting up KMK ?

From the [firmware downloads page](https://circuitpython.org/downloads?q=2040) I have tried the following : Adafruit KB2040, Sparkfun Pro Micro RP2040 and even the Raspberry Pi Pico.

None of the seem to work and the device boots back named just RPI-RP2 rather than CIRCUIT-PY or similar as it does in the RPI Pico board.

Any help on setting up the Lily58 keyboard would be appreciated.

**Comment by plut0nium** [comment]
According to issue #5 this depends on the model and characteristics of the NOR flash chip that was used.

I do not have any experience with CircuitPython and/or KMK, so I'm afraid I can't provide any support on this matter.
This repository is dedicated on the hardware design of the controller board.

**Comment by bharathyes** [comment]
Okay thanks. Will follow that issue to keep track of when support is added.
