### ISSUE TITLE
About Bom

### ISSUE THREAD

**Issue by F1hone** [plut0nium/0xB2#3]
Hello，this is a great project

I want to try to make a board myself

Could you please provide the bom sheet related to this project?

This will help me a lot, thanks

**Comment by bstiq** [comment]
Hi,

The latest gerber, BOM and POS files are in the release section of this repo.
Please note, at the moment the flash chip is not available at JLC (it's possible to order it but will take some time)

**Comment by F1hone** [comment]
![_UGRCYNHUO@1_~0@`{VOJ16](https://user-images.githubusercontent.com/87873287/183390861-adc04d4b-2100-45db-a067-5313034ef520.jpg)
Yes！
 i made it 
nice design

**Comment by F1hone** [comment]
![image](https://user-images.githubusercontent.com/87873287/183391467-0e5b4728-7555-406f-8297-b0f07379e55d.png)

**Comment by bstiq** [comment]
Hi,

I'm glad you figured it out ! Enjoy the rp2040's power.

I'll close this issue, feel free to reopen it if there's any questions.

Here is the pinout if necessary:
![image](https://user-images.githubusercontent.com/1847115/183440773-e1adfc91-151c-46a4-a989-f304193b1998.png)
