### ISSUE TITLE
About KMK

### ISSUE THREAD

**Issue by F1hone** [plut0nium/0xB2#5]
How should this board support kmk?
I use it as a Raspberry Pi Pico, nothing happens after flashing the uf2 file of CircuitPython 7.3.2,
What should I do to make it work like a Raspberry Pi Pico, or make him kmk compatible

**Comment by plut0nium** [comment]
Sorry, I don't know anything about CircuitPython and/or KMK...

But have you tried with the Sparkfun RP2040 version of CircuitPython: https://circuitpython.org/board/sparkfun_pro_micro_rp2040/ ?

**Comment by F1hone** [comment]
It doesn't work,
I tried other rp2040 boards and none of them worked
Maybe I need to compile a uf2 file myself

**Comment by plut0nium** [comment]
> I tried other rp2040 boards and none of them worked

If I understand correctly, this issue is not specific to this board.

**Comment by mitswan** [comment]
Has anyone found a workaround for getting Circuitpython on this? Having the same challenge

Is there something fundamentally different between the Splinky and the SparkFun / ItsyBitsy / MakerPi / Feather?

**Comment by mitswan** [comment]
For what its worth - the main difference is the flash chip GD25Q80C is not yet supported by circuitpython

**Comment by bharathyes** [comment]
@mitswan where best to check / track when support for this board is added ?
