### ISSUE TITLE
Flashing

### ISSUE THREAD

**Issue by sopsupreme** [plut0nium/0xB2#6]
hello, in order to use the splinky with QMK what should i flash the board with? 
I am struggling to find firmware that works with it, so far only micropython https://micropython.org/download/rp2-pico/ , which is non-hid compliant and cannot be used with QMK toolbox. QMK is also unable to compile in UF2 files,

**Comment by plut0nium** [comment]
Bastardkb has a number of example configs to use QMK on the Splinky: Scylla or Charybdis v2, Dilemma...

See here : https://github.com/qmk/qmk_firmware/tree/master/keyboards/bastardkb

[edit] these configs will produce a uf2 firmware image

**Comment by sopsupreme** [comment]
i got it working! thankyou!
