### ISSUE TITLE
Suggestion: Make a stamp hole panel variant

### ISSUE THREAD

**Issue by Ardakilic** [plut0nium/0xB2#9]
Hello,

I'm currently producing this board, and I choose economics for parts placements, considering I will solder the connectors myself. When I do like it, the v-cut makes it 20 usd more expensive for production.

As an alternative, JLCPCB suggested using stamp holes, and updated my gerber like this:

![pcb update gerber](https://user-images.githubusercontent.com/2063957/215254802-d826746b-ed12-4b13-a6de-7c1d74944f18.png)

So, when I decide to solder the connector myself, and use stamp holes instead of v-cut, it's almost $1 cheaper per module when you get 30 modules, just because of the selections.

I'd appreciate if this could be considered for future releases.

Thanks again for making this board available, can't wait to hold on the prototypes 😊

**Comment by Ardakilic** [comment]
Just a heads-up, I just received this:

![image](https://user-images.githubusercontent.com/2063957/218734965-1f8f06e9-1a75-4568-a434-534f447b092e.png)

![image](https://user-images.githubusercontent.com/2063957/218734999-78ea1b16-e1e2-43fb-bb6d-84daced2e753.png)

![image](https://user-images.githubusercontent.com/2063957/218735031-fbf924d5-32d6-44be-a885-0508e8e2cfcd.png)

I'll let you know how it will all go.

**Comment by Ardakilic** [comment]
This all worked nicely. I got all of the assembled boards without issues, and all are running nicely. I hope this is considered for the future releases!

**Comment by alinelena** [comment]
the other option is to let jlcpcb panelize them for you... bad news is you get 12 on a panel...

**Comment by Ardakilic** [comment]
@alinelena the issue is that in my country there's an imports limit. If I buy and ask JLC to panel it, for 30 boards, where each panel has 6, it'll be counted as 30 in the invoice, and it may create issues fore me. However, if I introduce the panel myself, technically, I'm buying just 5 parts.

**Comment by plut0nium** [comment]
Thanks for the feedback.

However, there are many panelizing options, some are more suited for specific uses (auto vs manual PCB assembly, cost optimization...).
The panelized version in the release is just provided for convenience, but the main deliverable remains the single-pcb cad files.

People are encouraged to panelize themselves to meet their application requirements.
